# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-26 07:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('Open', 'Open'), ('Closed', 'Closed')], default=0, max_length=7),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Final', 'Final'), ('Unassigned', 'Unassigned'), ('Assigned', 'Assigned'), ('Completed', 'Completed'), ('Late', 'Late'), ('Not Submitted', 'Not Submitted')], default=2, max_length=14),
        ),
    ]
