# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-03 05:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_activitylog_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='action_list',
        ),
        migrations.RemoveField(
            model_name='project',
            name='activity_log',
        ),
        migrations.AddField(
            model_name='actionlist',
            name='project',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='users.Project'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='activitylog',
            name='project',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='users.Project'),
            preserve_default=False,
        ),
    ]
