# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-22 14:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20170322_1917'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='est_start',
            new_name='start_date',
        ),
        migrations.RemoveField(
            model_name='task',
            name='actual_start',
        ),
    ]
