# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-22 15:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20170322_2255'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='users',
        ),
    ]
