# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-22 16:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_remove_task_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='users',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
