# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-22 17:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_task_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='to_leader',
            field=models.NullBooleanField(verbose_name='Is the leader working on this Task?'),
        ),
    ]
