# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-22 17:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_task_to_leader'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memberuser',
            name='tasks',
        ),
        migrations.AddField(
            model_name='task',
            name='members',
            field=models.ManyToManyField(to='users.MemberUser'),
        ),
        migrations.AlterField(
            model_name='task',
            name='start_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
