# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-25 04:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_remove_task_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(blank=True, default=django.utils.timezone.now, max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
